### PR TITLE
added secretbox detached

### PR DESCRIPTION
**Pull request by artenator**

### CODE REVIEW

**Comment by lvh** [comment]
Hey @artenator! Thanks for your contribution. Currently, this lacks tests. Ideally, could you find KAT (known-answer tests) for this API from somewhere else (libsodium upstream probably has some) so that we can check that it actually works?

**Comment by artenator** [comment]
Hey! 

I found a test for secretbox on the libsodium repository. Please see here: 
https://github.com/jedisct1/libsodium/blob/master/test/default/secretbox.c
https://github.com/jedisct1/libsodium/blob/master/test/default/secretbox.exp

I removed 32 bytes worth of 0 paddingfrom the test vector because the detached api handles padding the message with 0's before performing encryption. See here:
https://github.com/jedisct1/libsodium/blob/master/src/libsodium/crypto_secretbox/crypto_secretbox_easy.c

Let me know what you think... Thanks!

Arte

**Comment by lvh** [comment]
Awesome, great job @artenator ! Would you like to do the honors of updating the changelog? If so this looks good to merge to me.

**Comment by artenator** [comment]
Thanks @lvh !

I have updated the changelog. Let me know what you think.

Arte

**Comment by lvh** [comment]
Thanks!

**Pull request merged**
